{{- if .Values.secrets }}
{{- range $key, $value := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" $ }}-{{ $key }}
  labels:
    {{- include "todo-chatbot.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $secretKey, $secretValue := $value }}
  {{ $secretKey }}: {{ $secretValue | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}